title: Premerger observation and characterization of super-massive black hole binaries

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns:
    - Parameter_Estimation/*.ipynb

# This means only stuff in the table of contents
# note that if we have run the 'environment building' instructions, there will be
# a bunch of pycbc stuff which we don't need to run
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/icg-gravwaves/lisa_premerger_paper/
  branch: main 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  config:
    nb_execution_timeout: 5000
