theme: jekyll-theme-slate
title: Premerger observation and characterization of super-massive black hole binaries
url: "https://icg-gravwaves.github.io/lisa_premerger_paper/"
plugins:
  - jekyll-sitemap